name: CI

on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input for the workflow'
        required: false
        default: 'default_value'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scrapy psycopg2-binary python-dotenv

    - name: Run Scrapy spider
      run: scrapy crawl items
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        PGHOST: ${{ secrets.PGHOST }}
        PGPORT: ${{ secrets.PGPORT }}
        PGDATABASE: ${{ secrets.PGDATABASE }}
        PGUSER: ${{ secrets.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}

    - name: Insert data into database
      run: python ./steam/insert_views_to_db.py 
      env:
        PGHOST: ${{ secrets.PGHOST }}
        PGPORT: ${{ secrets.PGPORT }}
        PGDATABASE: ${{ secrets.PGDATABASE }}
        PGUSER: ${{ secrets.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
    
    - name: Scrape site and Insert tags into database
      run: python ./steam/scrape_site.py 
      env:
        PGHOST: ${{ secrets.PGHOST }}
        PGPORT: ${{ secrets.PGPORT }}
        PGDATABASE: ${{ secrets.PGDATABASE }}
        PGUSER: ${{ secrets.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
